# See: https://sw.kovidgoyal.net/kitty/conf/

###################
# Reset
###################

clear_all_shortcuts yes

###################
# OS
###################

map cmd+enter         toggle_fullscreen
map cmd+c             copy_to_clipboard
map cmd+v             paste_from_clipboard

###################
# Actions
###################

map cmd+r clear_terminal to_cursor active

###################
# Hints
###################

map cmd+p kitten hints --type path
map cmd+l kitten hints --type linenum --linenum-action code -g {path}:{line}

###################
# Fonts
###################

font_family      Dank Mono Regular
font_size 18.0

map cmd+equal    change_font_size all +2.0
map cmd+minus    change_font_size all -2.0
map cmd+0        change_font_size all 0

###################
# Alarms
###################

enable_audio_bell no
bell_on_tab no

###################
# Find
###################

map cmd+f launch --stdin-source=@last_cmd_output --stdin-add-formatting --type=overlay less +G -R
map cmd+shift+f launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay +G -R

###################
# Hyperlinks
###################

mouse_map cmd+left release grabbed,ungrabbed mouse_click_url
mouse_map cmd+left press grabbed mouse_discard_event

###################
# Tabs
###################

map cmd+t new_tab_with_cwd
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

###################
# Windows
###################

enabled_layouts      splits
map cmd+d            launch --location=vsplit --cwd=current
map cmd+shift+d      launch --location=hsplit --cwd=current
map cmd+w            close_window
map cmd+h            hide_macos_app
map cmd+]            next_window
map cmd+[            previous_window
map cmd+shift+j      move_window top
map cmd+shift+h      move_window left
map cmd+shift+k      move_window bottom
map cmd+shift+l      move_window right
map cmd+shift+left   resize_window narrower
map cmd+shift+right  resize_window wider
map cmd+shift+up     resize_window taller
map cmd+shift+down   resize_window shorter

###################
# Theme (https://github.com/catppuccin/kitty/blob/b14e8385c827f2d41660b71c7fec1e92bdcf2676/themes/mocha.conf)
###################

# The basic colors
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8
